/*=============================================== Common types ===============================================*/

/*==================== Fajny icons ====================*/

const fajnyIcons = {
    "arrow-down-circle-full-solid": "arrow-down-circle-full-solid",
    "arrow-down-circle-regular": "arrow-down-circle-regular",
    "arrow-down-circle-solid": "arrow-down-circle-solid",
    "arrow-down-regular": "arrow-down-regular",
    "arrow-down-solid": "arrow-down-solid",
    "arrow-down-up-regular": "arrow-down-up-regular",
    "arrow-down-up-solid": "arrow-down-up-solid",
    "arrow-left-circle-full-solid": "arrow-left-circle-full-solid",
    "arrow-left-circle-regular": "arrow-left-circle-regular",
    "arrow-left-circle-solid": "arrow-left-circle-solid",
    "arrow-left-regular": "arrow-left-regular",
    "arrow-left-solid": "arrow-left-solid",
    "arrow-left-right-regular": "arrow-left-right-regular",
    "arrow-left-right-solid": "arrow-left-right-solid",
    "arrow-left-up-right-down-regular": "arrow-left-up-right-down-regular",
    "arrow-left-up-right-down-solid": "arrow-left-up-right-down-solid",
    "arrow-right-circle-full-solid": "arrow-right-circle-full-solid",
    "arrow-right-circle-regular": "arrow-right-circle-regular",
    "arrow-right-circle-solid": "arrow-right-circle-solid",
    "arrow-right-left-regular": "arrow-right-left-regular",
    "arrow-right-left-solid": "arrow-right-left-solid",
    "arrow-right-regular": "arrow-right-regular",
    "arrow-right-solid": "arrow-right-solid",
    "arrow-right-up-left-down-regular": "arrow-right-up-left-down-regular",
    "arrow-right-up-left-down-solid": "arrow-right-up-left-down-solid",
    "arrow-up-circle-full-solid": "arrow-up-circle-full-solid",
    "arrow-up-circle-regular": "arrow-up-circle-regular",
    "arrow-up-circle-solid": "arrow-up-circle-solid",
    "arrow-up-down-regular": "arrow-up-down-regular",
    "arrow-up-down-solid": "arrow-up-down-solid",
    "arrow-up-regular": "arrow-up-regular",
    "arrow-up-solid": "arrow-up-solid",
    "caret-down-regular": "caret-down-regular",
    "caret-down-solid": "caret-down-solid",
    "caret-left-regular": "caret-left-regular",
    "caret-left-solid": "caret-left-solid",
    "caret-left-right-regular": "caret-left-right-regular",
    "caret-left-right-solid": "caret-left-right-solid",
    "caret-right-regular": "caret-right-regular",
    "caret-right-solid": "caret-right-solid",
    "caret-up-down-regular": "caret-up-down-regular",
    "caret-up-down-solid": "caret-up-down-solid",
    "caret-up-regular": "caret-up-regular",
    "caret-up-solid": "caret-up-solid",
    "chevron-down-regular": "chevron-down-regular",
    "chevron-down-solid": "chevron-down-solid",
    "chevron-left-regular": "chevron-left-regular",
    "chevron-left-solid": "chevron-left-solid",
    "chevron-left-right-regular": "chevron-left-right-regular",
    "chevron-left-right-solid": "chevron-left-right-solid",
    "chevron-right-regular": "chevron-right-regular",
    "chevron-right-solid": "chevron-right-solid",
    "chevron-up-down-regular": "chevron-up-down-regular",
    "chevron-up-down-solid": "chevron-up-down-solid",
    "chevron-up-regular": "chevron-up-regular",
    "chevron-up-solid": "chevron-up-solid",
    "double-chevron-down-regular": "double-chevron-down-regular",
    "double-chevron-down-solid": "double-chevron-down-solid",
    "double-chevron-left-regular": "double-chevron-left-regular",
    "double-chevron-left-solid": "double-chevron-left-solid",
    "double-chevron-right-regular": "double-chevron-right-regular",
    "double-chevron-right-solid": "double-chevron-right-solid",
    "double-chevron-up-regular": "double-chevron-up-regular",
    "double-chevron-up-solid": "double-chevron-up-solid",
    "maximise-regular": "maximise-regular",
    "maximise-solid": "maximise-solid",
    "minimize-regular": "minimize-regular",
    "minimize-solid": "minimize-solid",
    "american-express-brand": "american-express-brand",
    "american-express-card-brand": "american-express-card-brand",
    "angular-brand": "angular-brand",
    "apple-brand": "apple-brand",
    "apple-music-brand": "apple-music-brand",
    "apple-pay-badge-brand": "apple-pay-badge-brand",
    "apple-pay-brand": "apple-pay-brand",
    "apple-pay-card-brand": "apple-pay-card-brand",
    "atlassian-alt-brand": "atlassian-alt-brand",
    "atlassian-brand": "atlassian-brand",
    "behance-brand": "behance-brand",
    "behance-square-brand": "behance-square-brand",
    "bitbucket-alt-brand": "bitbucket-alt-brand",
    "bitbucket-brand": "bitbucket-brand",
    "bluetooth-alt-brand": "bluetooth-alt-brand",
    "bluetooth-brand": "bluetooth-brand",
    "chrome-brand": "chrome-brand",
    "chromecast-brand": "chromecast-brand",
    "chromecast-cast-brand": "chromecast-cast-brand",
    "codepen-alt-brand": "codepen-alt-brand",
    "codepen-brand": "codepen-brand",
    "codepen-circle-brand": "codepen-circle-brand",
    "confluence-alt-brand": "confluence-alt-brand",
    "confluence-brand": "confluence-brand",
    "css-brand": "css-brand",
    "diners-club-brand": "diners-club-brand",
    "diners-club-card-brand": "diners-club-card-brand",
    "docker-alt-brand": "docker-alt-brand",
    "docker-brand": "docker-brand",
    "dribbble-alt-brand": "dribbble-alt-brand",
    "dribbble-brand": "dribbble-brand",
    "dribbble-square-brand": "dribbble-square-brand",
    "dropbox-alt-brand": "dropbox-alt-brand",
    "dropbox-brand": "dropbox-brand",
    "ebay-brand": "ebay-brand",
    "edge-brand": "edge-brand",
    "facebook-brand": "facebook-brand",
    "facebook-square-brand": "facebook-square-brand",
    "fajny-css-brand": "fajny-css-brand",
    "figma-brand": "figma-brand",
    "firefox-brand": "firefox-brand",
    "github-brand": "github-brand",
    "github-square-brand": "github-square-brand",
    "gitlab-alt-brand": "gitlab-alt-brand",
    "gitlab-brand": "gitlab-brand",
    "google-alt-brand": "google-alt-brand",
    "google-brand": "google-brand",
    "google-cardboard-brand": "google-cardboard-brand",
    "google-drive-brand": "google-drive-brand",
    "html-brand": "html-brand",
    "instagram-brand": "instagram-brand",
    "internet-explorer-brand": "internet-explorer-brand",
    "itunes-brand": "itunes-brand",
    "java-brand": "java-brand",
    "javascript-brand": "javascript-brand",
    "jira-align-alt-brand": "jira-align-alt-brand",
    "jira-align-brand": "jira-align-brand",
    "jira-software-alt-brand": "jira-software-alt-brand",
    "jira-software-brand": "jira-software-brand",
    "less-brand": "less-brand",
    "linkedin-alt-brand": "linkedin-alt-brand",
    "linkedin-brand": "linkedin-brand",
    "linkedin-square-brand": "linkedin-square-brand",
    "linux-brand": "linux-brand",
    "mastercard-brand": "mastercard-brand",
    "mastercard-card-brand": "mastercard-card-brand",
    "medium-brand": "medium-brand",
    "medium-square-brand": "medium-square-brand",
    "messenger-brand": "messenger-brand",
    "microsoft-alt-brand": "microsoft-alt-brand",
    "microsoft-brand": "microsoft-brand",
    "node-brand": "node-brand",
    "npm-brand": "npm-brand",
    "opera-alt-brand": "opera-alt-brand",
    "opera-brand": "opera-brand",
    "paypal-alt-brand": "paypal-alt-brand",
    "paypal-brand": "paypal-brand",
    "paypal-card-brand": "paypal-card-brand",
    "php-brand": "php-brand",
    "pinterest-alt-brand": "pinterest-alt-brand",
    "pinterest-brand": "pinterest-brand",
    "pinterest-square-brand": "pinterest-square-brand",
    "playstation-brand": "playstation-brand",
    "python-alt-brand": "python-alt-brand",
    "python-brand": "python-brand",
    "react-brand": "react-brand",
    "safari-brand": "safari-brand",
    "sass-alt-brand": "sass-alt-brand",
    "sass-brand": "sass-brand",
    "sketch-brand": "sketch-brand",
    "skype-brand": "skype-brand",
    "slack-alt-brand": "slack-alt-brand",
    "slack-brand": "slack-brand",
    "snapchat-brand": "snapchat-brand",
    "snapchat-square-brand": "snapchat-square-brand",
    "sourcetree-alt-brand": "sourcetree-alt-brand",
    "sourcetree-brand": "sourcetree-brand",
    "squarespace-alt-brand": "squarespace-alt-brand",
    "squarespace-brand": "squarespace-brand",
    "stack-overflow-alt-brand": "stack-overflow-alt-brand",
    "stack-overflow-brand": "stack-overflow-brand",
    "stadia-alt-brand": "stadia-alt-brand",
    "stadia-brand": "stadia-brand",
    "steam-alt-brand": "steam-alt-brand",
    "steam-brand": "steam-brand",
    "telegram-brand": "telegram-brand",
    "tiktok-brand": "tiktok-brand",
    "tiktok-square-brand": "tiktok-square-brand",
    "trello-alt-brand": "trello-alt-brand",
    "trello-brand": "trello-brand",
    "twitter-brand": "twitter-brand",
    "twitter-square-brand": "twitter-square-brand",
    "unity-alt-brand": "unity-alt-brand",
    "unity-brand": "unity-brand",
    "unsplash-alt-brand": "unsplash-alt-brand",
    "unsplash-brand": "unsplash-brand",
    "usb-brand": "usb-brand",
    "visa-brand": "visa-brand",
    "visa-card-brand": "visa-card-brand",
    "wikipedia-w-brand": "wikipedia-w-brand",
    "windows-brand": "windows-brand",
    "wordpress-alt-brand": "wordpress-alt-brand",
    "wordpress-brand": "wordpress-brand",
    "xbox-brand": "xbox-brand",
    "xing-alt-brand": "xing-alt-brand",
    "xing-brand": "xing-brand",
    "xing-square-brand": "xing-square-brand",
    "youtube-alt-brand": "youtube-alt-brand",
    "youtube-brand": "youtube-brand",
    "youtube-square-brand": "youtube-square-brand",
    "bubble-message-check-regular": "bubble-message-check-regular",
    "bubble-message-check-solid": "bubble-message-check-solid",
    "bubble-message-code-regular": "bubble-message-code-regular",
    "bubble-message-code-solid": "bubble-message-code-solid",
    "bubble-message-dots-regular": "bubble-message-dots-regular",
    "bubble-message-dots-solid": "bubble-message-dots-solid",
    "bubble-message-edit-regular": "bubble-message-edit-regular",
    "bubble-message-edit-solid": "bubble-message-edit-solid",
    "bubble-message-exclamation-regular": "bubble-message-exclamation-regular",
    "bubble-message-exclamation-solid": "bubble-message-exclamation-solid",
    "bubble-message-lines-regular": "bubble-message-lines-regular",
    "bubble-message-lines-solid": "bubble-message-lines-solid",
    "bubble-message-minus-regular": "bubble-message-minus-regular",
    "bubble-message-minus-solid": "bubble-message-minus-solid",
    "bubble-message-plus-regular": "bubble-message-plus-regular",
    "bubble-message-plus-solid": "bubble-message-plus-solid",
    "bubble-message-regular": "bubble-message-regular",
    "bubble-message-solid": "bubble-message-solid",
    "bubble-message-slash-regular": "bubble-message-slash-regular",
    "bubble-message-slash-solid": "bubble-message-slash-solid",
    "bubbles-message-regular": "bubbles-message-regular",
    "bubbles-message-solid": "bubbles-message-solid",
    "mail-open-letter-regular": "mail-open-letter-regular",
    "mail-open-letter-solid": "mail-open-letter-solid",
    "mail-open-regular": "mail-open-regular",
    "mail-open-solid": "mail-open-solid",
    "mail-regular": "mail-regular",
    "mail-solid": "mail-solid",
    "paperplane-regular": "paperplane-regular",
    "paperplane-solid": "paperplane-solid",
    "calendar-check-regular": "calendar-check-regular",
    "calendar-check-solid": "calendar-check-solid",
    "calendar-days-regular": "calendar-days-regular",
    "calendar-days-solid": "calendar-days-solid",
    "calendar-minus-regular": "calendar-minus-regular",
    "calendar-minus-solid": "calendar-minus-solid",
    "calendar-plus-regular": "calendar-plus-regular",
    "calendar-plus-solid": "calendar-plus-solid",
    "calendar-regular": "calendar-regular",
    "calendar-solid": "calendar-solid",
    "clock-full-solid": "clock-full-solid",
    "clock-regular": "clock-regular",
    "clock-solid": "clock-solid",
    "compass-regular": "compass-regular",
    "compass-solid": "compass-solid",
    "fast-regular": "fast-regular",
    "fast-solid": "fast-solid",
    "hourglass-regular": "hourglass-regular",
    "hourglass-solid": "hourglass-solid",
    "location-arrow-regular": "location-arrow-regular",
    "location-arrow-solid": "location-arrow-solid",
    "map-pin-regular": "map-pin-regular",
    "map-pin-solid": "map-pin-solid",
    "map-regular": "map-regular",
    "map-solid": "map-solid",
    "pin-regular": "pin-regular",
    "pin-solid": "pin-solid",
    "stopwatch-regular": "stopwatch-regular",
    "stopwatch-solid": "stopwatch-solid",
    "chart-bar-regular": "chart-bar-regular",
    "chart-bar-solid": "chart-bar-solid",
    "divide-regular": "divide-regular",
    "divide-solid": "divide-solid",
    "equal-regular": "equal-regular",
    "equal-solid": "equal-solid",
    "inferior-or-equal-regular": "inferior-or-equal-regular",
    "inferior-or-equal-solid": "inferior-or-equal-solid",
    "inferior-regular": "inferior-regular",
    "inferior-solid": "inferior-solid",
    "minus-circle-full-solid": "minus-circle-full-solid",
    "minus-circle-regular": "minus-circle-regular",
    "minus-circle-solid": "minus-circle-solid",
    "minus-regular": "minus-regular",
    "minus-solid": "minus-solid",
    "not-equal-regular": "not-equal-regular",
    "not-equal-solid": "not-equal-solid",
    "octagon-minus-full-solid": "octagon-minus-full-solid",
    "octagon-minus-regular": "octagon-minus-regular",
    "octagon-minus-solid": "octagon-minus-solid",
    "octagon-plus-full-solid": "octagon-plus-full-solid",
    "octagon-plus-regular": "octagon-plus-regular",
    "octagon-plus-solid": "octagon-plus-solid",
    "percentage-regular": "percentage-regular",
    "percentage-solid": "percentage-solid",
    "piechart-regular": "piechart-regular",
    "piechart-solid": "piechart-solid",
    "plus-circle-full-solid": "plus-circle-full-solid",
    "plus-circle-regular": "plus-circle-regular",
    "plus-circle-solid": "plus-circle-solid",
    "plus-minus-regular": "plus-minus-regular",
    "plus-minus-solid": "plus-minus-solid",
    "plus-regular": "plus-regular",
    "plus-solid": "plus-solid",
    "slash-regular": "slash-regular",
    "slash-solid": "slash-solid",
    "superior-or-equal-regular": "superior-or-equal-regular",
    "superior-or-equal-solid": "superior-or-equal-solid",
    "superior-regular": "superior-regular",
    "superior-solid": "superior-solid",
    "bone-regular": "bone-regular",
    "bone-solid": "bone-solid",
    "circle-full-solid": "circle-full-solid",
    "circle-regular": "circle-regular",
    "circle-solid": "circle-solid",
    "crosshair-regular": "crosshair-regular",
    "crosshair-solid": "crosshair-solid",
    "globe-regular": "globe-regular",
    "globe-solid": "globe-solid",
    "hashtag-regular": "hashtag-regular",
    "hashtag-solid": "hashtag-solid",
    "home-regular": "home-regular",
    "home-solid": "home-solid",
    "lightning-regular": "lightning-regular",
    "lightning-solid": "lightning-solid",
    "molecule-full-solid": "molecule-full-solid",
    "molecule-regular": "molecule-regular",
    "molecule-solid": "molecule-solid",
    "moon-regular": "moon-regular",
    "moon-solid": "moon-solid",
    "paw-regular": "paw-regular",
    "paw-solid": "paw-solid",
    "planet-regular": "planet-regular",
    "planet-solid": "planet-solid",
    "rocket-regular": "rocket-regular",
    "rocket-solid": "rocket-solid",
    "sun-regular": "sun-regular",
    "sun-solid": "sun-solid",
    "bullseye-arrow-regular": "bullseye-arrow-regular",
    "bullseye-arrow-solid": "bullseye-arrow-solid",
    "bullseye-pointer-regular": "bullseye-pointer-regular",
    "bullseye-pointer-solid": "bullseye-pointer-solid",
    "bullseye-regular": "bullseye-regular",
    "bullseye-solid": "bullseye-solid",
    "camera-regular": "camera-regular",
    "camera-solid": "camera-solid",
    "color-palette-regular": "color-palette-regular",
    "color-palette-solid": "color-palette-solid",
    "cookie-regular": "cookie-regular",
    "cookie-solid": "cookie-solid",
    "donut-regular": "donut-regular",
    "donut-solid": "donut-solid",
    "erlenmeyer-filled-regular": "erlenmeyer-filled-regular",
    "erlenmeyer-filled-solid": "erlenmeyer-filled-solid",
    "erlenmeyer-regular": "erlenmeyer-regular",
    "erlenmeyer-solid": "erlenmeyer-solid",
    "gift-regular": "gift-regular",
    "gift-solid": "gift-solid",
    "headphones-regular": "headphones-regular",
    "headphones-solid": "headphones-solid",
    "key-regular": "key-regular",
    "key-solid": "key-solid",
    "lightbulb-exclamation-regular": "lightbulb-exclamation-regular",
    "lightbulb-exclamation-solid": "lightbulb-exclamation-solid",
    "lightbulb-on-regular": "lightbulb-on-regular",
    "lightbulb-on-solid": "lightbulb-on-solid",
    "lightbulb-regular": "lightbulb-regular",
    "lightbulb-solid": "lightbulb-solid",
    "medal-regular": "medal-regular",
    "medal-solid": "medal-solid",
    "mug-regular": "mug-regular",
    "mug-solid": "mug-solid",
    "newspaper-regular": "newspaper-regular",
    "newspaper-solid": "newspaper-solid",
    "temperature-regular": "temperature-regular",
    "temperature-solid": "temperature-solid",
    "wand-regular": "wand-regular",
    "wand-solid": "wand-solid",
    "book-open-regular": "book-open-regular",
    "book-open-solid": "book-open-solid",
    "book-regular": "book-regular",
    "book-solid": "book-solid",
    "box-open-regular": "box-open-regular",
    "box-open-solid": "box-open-solid",
    "box-regular": "box-regular",
    "box-solid": "box-solid",
    "clipboard-check-regular": "clipboard-check-regular",
    "clipboard-check-solid": "clipboard-check-solid",
    "clipboard-list-regular": "clipboard-list-regular",
    "clipboard-list-solid": "clipboard-list-solid",
    "clipboard-regular": "clipboard-regular",
    "clipboard-solid": "clipboard-solid",
    "file-code-regular": "file-code-regular",
    "file-code-solid": "file-code-solid",
    "file-download-regular": "file-download-regular",
    "file-download-solid": "file-download-solid",
    "file-lock-regular": "file-lock-regular",
    "file-lock-solid": "file-lock-solid",
    "file-regular": "file-regular",
    "file-solid": "file-solid",
    "file-search-regular": "file-search-regular",
    "file-search-solid": "file-search-solid",
    "file-upload-regular": "file-upload-regular",
    "file-upload-solid": "file-upload-solid",
    "file-user-regular": "file-user-regular",
    "file-user-solid": "file-user-solid",
    "files-regular": "files-regular",
    "files-solid": "files-solid",
    "folder-close-regular": "folder-close-regular",
    "folder-close-solid": "folder-close-solid",
    "folder-minus-regular": "folder-minus-regular",
    "folder-minus-solid": "folder-minus-solid",
    "folder-open-regular": "folder-open-regular",
    "folder-open-solid": "folder-open-solid",
    "folder-plus-regular": "folder-plus-regular",
    "folder-plus-solid": "folder-plus-solid",
    "folder-regular": "folder-regular",
    "folder-solid": "folder-solid",
    "folder-tree-regular": "folder-tree-regular",
    "folder-tree-solid": "folder-tree-solid",
    "paperclip-regular": "paperclip-regular",
    "paperclip-solid": "paperclip-solid",
    "sticky-note-regular": "sticky-note-regular",
    "sticky-note-solid": "sticky-note-solid",
    "female-regular": "female-regular",
    "female-solid": "female-solid",
    "male-regular": "male-regular",
    "male-solid": "male-solid",
    "transgender-regular": "transgender-regular",
    "transgender-solid": "transgender-solid",
    "user-card-clip-regular": "user-card-clip-regular",
    "user-card-clip-solid": "user-card-clip-solid",
    "user-card-regular": "user-card-regular",
    "user-card-solid": "user-card-solid",
    "user-check-regular": "user-check-regular",
    "user-check-solid": "user-check-solid",
    "user-circle-regular": "user-circle-regular",
    "user-circle-solid": "user-circle-solid",
    "user-clock-regular": "user-clock-regular",
    "user-clock-solid": "user-clock-solid",
    "user-close-regular": "user-close-regular",
    "user-close-solid": "user-close-solid",
    "user-cog-regular": "user-cog-regular",
    "user-cog-solid": "user-cog-solid",
    "user-edit-regular": "user-edit-regular",
    "user-edit-solid": "user-edit-solid",
    "user-lock-regular": "user-lock-regular",
    "user-lock-solid": "user-lock-solid",
    "user-minus-regular": "user-minus-regular",
    "user-minus-solid": "user-minus-solid",
    "user-plus-regular": "user-plus-regular",
    "user-plus-solid": "user-plus-solid",
    "user-regular": "user-regular",
    "user-solid": "user-solid",
    "user-shield-regular": "user-shield-regular",
    "user-shield-solid": "user-shield-solid",
    "user-slash-regular": "user-slash-regular",
    "user-slash-solid": "user-slash-solid",
    "users-three-regular": "users-three-regular",
    "users-three-solid": "users-three-solid",
    "users-two-regular": "users-two-regular",
    "users-two-solid": "users-two-solid",
    "basket-regular": "basket-regular",
    "basket-solid": "basket-solid",
    "cart-arrow-regular": "cart-arrow-regular",
    "cart-arrow-solid": "cart-arrow-solid",
    "cart-minus-regular": "cart-minus-regular",
    "cart-minus-solid": "cart-minus-solid",
    "cart-percentage-regular": "cart-percentage-regular",
    "cart-percentage-solid": "cart-percentage-solid",
    "cart-plus-regular": "cart-plus-regular",
    "cart-plus-solid": "cart-plus-solid",
    "cart-regular": "cart-regular",
    "cart-solid": "cart-solid",
    "cash-regular": "cash-regular",
    "cash-solid": "cash-solid",
    "credit-card-regular": "credit-card-regular",
    "credit-card-solid": "credit-card-solid",
    "pricetag-regular": "pricetag-regular",
    "pricetag-solid": "pricetag-solid",
    "pricetags-regular": "pricetags-regular",
    "pricetags-solid": "pricetags-solid",
    "store-regular": "store-regular",
    "store-solid": "store-solid",
    "wallet-regular": "wallet-regular",
    "wallet-solid": "wallet-solid",
    "battery-charging-regular": "battery-charging-regular",
    "battery-charging-solid": "battery-charging-solid",
    "battery-empty-regular": "battery-empty-regular",
    "battery-empty-solid": "battery-empty-solid",
    "battery-full-regular": "battery-full-regular",
    "battery-full-solid": "battery-full-solid",
    "battery-half-regular": "battery-half-regular",
    "battery-half-solid": "battery-half-solid",
    "brackets-regular": "brackets-regular",
    "brackets-solid": "brackets-solid",
    "browser-window-close-regular": "browser-window-close-regular",
    "browser-window-close-solid": "browser-window-close-solid",
    "browser-window-minus-regular": "browser-window-minus-regular",
    "browser-window-minus-solid": "browser-window-minus-solid",
    "browser-window-plus-regular": "browser-window-plus-regular",
    "browser-window-plus-solid": "browser-window-plus-solid",
    "browser-window-regular": "browser-window-regular",
    "browser-window-solid": "browser-window-solid",
    "browser-windows-regular": "browser-windows-regular",
    "browser-windows-solid": "browser-windows-solid",
    "calculator-regular": "calculator-regular",
    "calculator-solid": "calculator-solid",
    "cloud-download-regular": "cloud-download-regular",
    "cloud-download-solid": "cloud-download-solid",
    "cloud-regular": "cloud-regular",
    "cloud-solid": "cloud-solid",
    "code-branch-regular": "code-branch-regular",
    "code-branch-solid": "code-branch-solid",
    "code-regular": "code-regular",
    "code-solid": "code-solid",
    "curly-brackets-regular": "curly-brackets-regular",
    "curly-brackets-solid": "curly-brackets-solid",
    "database-regular": "database-regular",
    "database-solid": "database-solid",
    "desktop-regular": "desktop-regular",
    "desktop-solid": "desktop-solid",
    "download-regular": "download-regular",
    "download-solid": "download-solid",
    "fingerprint-regular": "fingerprint-regular",
    "fingerprint-solid": "fingerprint-solid",
    "keyboard-regular": "keyboard-regular",
    "keyboard-solid": "keyboard-solid",
    "masonry-regular": "masonry-regular",
    "masonry-solid": "masonry-solid",
    "microchip-regular": "microchip-regular",
    "microchip-solid": "microchip-solid",
    "mobile-regular": "mobile-regular",
    "mobile-solid": "mobile-solid",
    "mobile-slash-regular": "mobile-slash-regular",
    "mobile-slash-solid": "mobile-slash-solid",
    "phone-arrow-bottom-left-regular": "phone-arrow-bottom-left-regular",
    "phone-arrow-bottom-left-solid": "phone-arrow-bottom-left-solid",
    "phone-arrow-up-right-regular": "phone-arrow-up-right-regular",
    "phone-arrow-up-right-solid": "phone-arrow-up-right-solid",
    "phone-minus-regular": "phone-minus-regular",
    "phone-minus-solid": "phone-minus-solid",
    "phone-plus-regular": "phone-plus-regular",
    "phone-plus-solid": "phone-plus-solid",
    "phone-regular": "phone-regular",
    "phone-solid": "phone-solid",
    "phone-slash-regular": "phone-slash-regular",
    "phone-slash-solid": "phone-slash-solid",
    "power-regular": "power-regular",
    "power-solid": "power-solid",
    "qr-code-regular": "qr-code-regular",
    "qr-code-solid": "qr-code-solid",
    "server-regular": "server-regular",
    "server-solid": "server-solid",
    "signal-0-bar-regular": "signal-0-bar-regular",
    "signal-0-bar-solid": "signal-0-bar-solid",
    "signal-1-bar-regular": "signal-1-bar-regular",
    "signal-1-bar-solid": "signal-1-bar-solid",
    "signal-2-bar-regular": "signal-2-bar-regular",
    "signal-2-bar-solid": "signal-2-bar-solid",
    "signal-3-bar-regular": "signal-3-bar-regular",
    "signal-3-bar-solid": "signal-3-bar-solid",
    "signal-4-bar-regular": "signal-4-bar-regular",
    "signal-4-bar-solid": "signal-4-bar-solid",
    "signal-5-bar-regular": "signal-5-bar-regular",
    "signal-5-bar-solid": "signal-5-bar-solid",
    "sitemap-regular": "sitemap-regular",
    "sitemap-solid": "sitemap-solid",
    "terminal-regular": "terminal-regular",
    "terminal-solid": "terminal-solid",
    "upload-regular": "upload-regular",
    "upload-solid": "upload-solid",
    "wifi-regular": "wifi-regular",
    "wifi-solid": "wifi-solid",
    "align-bottom-center-regular": "align-bottom-center-regular",
    "align-bottom-center-solid": "align-bottom-center-solid",
    "align-bottom-left-regular": "align-bottom-left-regular",
    "align-bottom-left-solid": "align-bottom-left-solid",
    "align-bottom-regular": "align-bottom-regular",
    "align-bottom-solid": "align-bottom-solid",
    "align-bottom-right-regular": "align-bottom-right-regular",
    "align-bottom-right-solid": "align-bottom-right-solid",
    "align-center-regular": "align-center-regular",
    "align-center-solid": "align-center-solid",
    "align-left-regular": "align-left-regular",
    "align-left-solid": "align-left-solid",
    "align-middle-center-regular": "align-middle-center-regular",
    "align-middle-center-solid": "align-middle-center-solid",
    "align-middle-left-regular": "align-middle-left-regular",
    "align-middle-left-solid": "align-middle-left-solid",
    "align-middle-regular": "align-middle-regular",
    "align-middle-solid": "align-middle-solid",
    "align-middle-right-regular": "align-middle-right-regular",
    "align-middle-right-solid": "align-middle-right-solid",
    "align-right-regular": "align-right-regular",
    "align-right-solid": "align-right-solid",
    "align-top-center-regular": "align-top-center-regular",
    "align-top-center-solid": "align-top-center-solid",
    "align-top-left-regular": "align-top-left-regular",
    "align-top-left-solid": "align-top-left-solid",
    "align-top-regular": "align-top-regular",
    "align-top-solid": "align-top-solid",
    "align-top-right-regular": "align-top-right-regular",
    "align-top-right-solid": "align-top-right-solid",
    "backslash-regular": "backslash-regular",
    "backslash-solid": "backslash-solid",
    "backward-regular": "backward-regular",
    "backward-solid": "backward-solid",
    "bell-regular": "bell-regular",
    "bell-solid": "bell-solid",
    "bell-slash-regular": "bell-slash-regular",
    "bell-slash-solid": "bell-slash-solid",
    "bookmark-full-solid": "bookmark-full-solid",
    "bookmark-regular": "bookmark-regular",
    "bookmark-solid": "bookmark-solid",
    "brightness-minus-regular": "brightness-minus-regular",
    "brightness-minus-solid": "brightness-minus-solid",
    "brightness-plus-regular": "brightness-plus-regular",
    "brightness-plus-solid": "brightness-plus-solid",
    "burger-alt-regular": "burger-alt-regular",
    "burger-alt-solid": "burger-alt-solid",
    "burger-regular": "burger-regular",
    "burger-solid": "burger-solid",
    "check-circle-full-solid": "check-circle-full-solid",
    "check-circle-regular": "check-circle-regular",
    "check-circle-solid": "check-circle-solid",
    "check-regular": "check-regular",
    "check-solid": "check-solid",
    "close-regular": "close-regular",
    "close-solid": "close-solid",
    "close-circle-full-solid": "close-circle-full-solid",
    "close-circle-regular": "close-circle-regular",
    "close-circle-solid": "close-circle-solid",
    "cog-regular": "cog-regular",
    "cog-solid": "cog-solid",
    "cogs-regular": "cogs-regular",
    "cogs-solid": "cogs-solid",
    "collection-regular": "collection-regular",
    "collection-solid": "collection-solid",
    "copy-regular": "copy-regular",
    "copy-solid": "copy-solid",
    "crop-regular": "crop-regular",
    "crop-solid": "crop-solid",
    "dashboard-regular": "dashboard-regular",
    "dashboard-solid": "dashboard-solid",
    "delete-regular": "delete-regular",
    "delete-solid": "delete-solid",
    "diamond-full-solid": "diamond-full-solid",
    "diamond-regular": "diamond-regular",
    "diamond-solid": "diamond-solid",
    "distribute-horizontal-regular": "distribute-horizontal-regular",
    "distribute-horizontal-solid": "distribute-horizontal-solid",
    "distribute-vertical-regular": "distribute-vertical-regular",
    "distribute-vertical-solid": "distribute-vertical-solid",
    "draw-circle-regular": "draw-circle-regular",
    "draw-circle-solid": "draw-circle-solid",
    "draw-square-regular": "draw-square-regular",
    "draw-square-solid": "draw-square-solid",
    "edit-regular": "edit-regular",
    "edit-solid": "edit-solid",
    "ellipsis-horizontal-solid": "ellipsis-horizontal-solid",
    "ellipsis-vertical-solid": "ellipsis-vertical-solid",
    "external-link-regular": "external-link-regular",
    "external-link-solid": "external-link-solid",
    "eye-regular": "eye-regular",
    "eye-solid": "eye-solid",
    "eye-slash-regular": "eye-slash-regular",
    "eye-slash-solid": "eye-slash-solid",
    "fast-backward-regular": "fast-backward-regular",
    "fast-backward-solid": "fast-backward-solid",
    "fast-forward-regular": "fast-forward-regular",
    "fast-forward-solid": "fast-forward-solid",
    "filter-close-regular": "filter-close-regular",
    "filter-close-solid": "filter-close-solid",
    "filter-minus-regular": "filter-minus-regular",
    "filter-minus-solid": "filter-minus-solid",
    "filter-plus-regular": "filter-plus-regular",
    "filter-plus-solid": "filter-plus-solid",
    "filter-regular": "filter-regular",
    "filter-solid": "filter-solid",
    "flag-full-regular": "flag-full-regular",
    "flag-full-solid": "flag-full-solid",
    "flag-regular": "flag-regular",
    "flag-solid": "flag-solid",
    "forward-regular": "forward-regular",
    "forward-solid": "forward-solid",
    "grid-horizontal-regular": "grid-horizontal-regular",
    "grid-horizontal-solid": "grid-horizontal-solid",
    "grid-regular": "grid-regular",
    "grid-solid": "grid-solid",
    "grid-vertical-regular": "grid-vertical-regular",
    "grid-vertical-solid": "grid-vertical-solid",
    "heart-full-regular": "heart-full-regular",
    "heart-full-solid": "heart-full-solid",
    "heart-regular": "heart-regular",
    "heart-solid": "heart-solid",
    "history-regular": "history-regular",
    "history-solid": "history-solid",
    "image-regular": "image-regular",
    "image-solid": "image-solid",
    "images-regular": "images-regular",
    "images-solid": "images-solid",
    "information-regular": "information-regular",
    "information-solid": "information-solid",
    "kebab-menu-regular": "kebab-menu-regular",
    "kebab-menu-solid": "kebab-menu-solid",
    "keyboard-brightness-minus-regular": "keyboard-brightness-minus-regular",
    "keyboard-brightness-minus-solid": "keyboard-brightness-minus-solid",
    "keyboard-brightness-plus-regular": "keyboard-brightness-plus-regular",
    "keyboard-brightness-plus-solid": "keyboard-brightness-plus-solid",
    "layer-group-regular": "layer-group-regular",
    "layer-group-solid": "layer-group-solid",
    "layer-minus-regular": "layer-minus-regular",
    "layer-minus-solid": "layer-minus-solid",
    "layer-plus-regular": "layer-plus-regular",
    "layer-plus-solid": "layer-plus-solid",
    "link-regular": "link-regular",
    "link-solid": "link-solid",
    "list-regular": "list-regular",
    "list-solid": "list-solid",
    "lock-open-regular": "lock-open-regular",
    "lock-open-solid": "lock-open-solid",
    "lock-regular": "lock-regular",
    "lock-solid": "lock-solid",
    "login-regular": "login-regular",
    "login-solid": "login-solid",
    "logout-regular": "logout-regular",
    "logout-solid": "logout-solid",
    "magnifying-glass-full-solid": "magnifying-glass-full-solid",
    "magnifying-glass-minus-full-solid": "magnifying-glass-minus-full-solid",
    "magnifying-glass-minus-regular": "magnifying-glass-minus-regular",
    "magnifying-glass-minus-solid": "magnifying-glass-minus-solid",
    "magnifying-glass-plus-full-solid": "magnifying-glass-plus-full-solid",
    "magnifying-glass-plus-regular": "magnifying-glass-plus-regular",
    "magnifying-glass-plus-solid": "magnifying-glass-plus-solid",
    "magnifying-glass-regular": "magnifying-glass-regular",
    "magnifying-glass-solid": "magnifying-glass-solid",
    "network-signal-regular": "network-signal-regular",
    "network-signal-solid": "network-signal-solid",
    "network-signal-slash-regular": "network-signal-slash-regular",
    "network-signal-slash-solid": "network-signal-slash-solid",
    "not-allowed-full-solid": "not-allowed-full-solid",
    "not-allowed-regular": "not-allowed-regular",
    "not-allowed-solid": "not-allowed-solid",
    "octagon-check-full-solid": "octagon-check-full-solid",
    "octagon-check-regular": "octagon-check-regular",
    "octagon-check-solid": "octagon-check-solid",
    "octagon-close-full-solid": "octagon-close-full-solid",
    "octagon-close-regular": "octagon-close-regular",
    "octagon-close-solid": "octagon-close-solid",
    "octagon-exclamation-full-solid": "octagon-exclamation-full-solid",
    "octagon-exclamation-regular": "octagon-exclamation-regular",
    "octagon-exclamation-solid": "octagon-exclamation-solid",
    "octagon-full-solid": "octagon-full-solid",
    "octagon-regular": "octagon-regular",
    "octagon-solid": "octagon-solid",
    "pause-regular": "pause-regular",
    "pause-solid": "pause-solid",
    "pen-regular": "pen-regular",
    "pen-solid": "pen-solid",
    "pencil-regular": "pencil-regular",
    "pencil-solid": "pencil-solid",
    "plane-regular": "plane-regular",
    "plane-solid": "plane-solid",
    "play-pause-regular": "play-pause-regular",
    "play-pause-solid": "play-pause-solid",
    "play-regular": "play-regular",
    "play-solid": "play-solid",
    "pointer-regular": "pointer-regular",
    "pointer-solid": "pointer-solid",
    "previous-regular": "previous-regular",
    "previous-solid": "previous-solid",
    "quit-regular": "quit-regular",
    "quit-solid": "quit-solid",
    "reload-regular": "reload-regular",
    "reload-solid": "reload-solid",
    "save-regular": "save-regular",
    "save-solid": "save-solid",
    "send-regular": "send-regular",
    "send-solid": "send-solid",
    "settings-regular": "settings-regular",
    "settings-solid": "settings-solid",
    "share-regular": "share-regular",
    "share-solid": "share-solid",
    "shield-check-regular": "shield-check-regular",
    "shield-check-solid": "shield-check-solid",
    "shield-close-regular": "shield-close-regular",
    "shield-close-solid": "shield-close-solid",
    "shield-minus-regular": "shield-minus-regular",
    "shield-minus-solid": "shield-minus-solid",
    "shield-plus-regular": "shield-plus-regular",
    "shield-plus-solid": "shield-plus-solid",
    "shield-regular": "shield-regular",
    "shield-solid": "shield-solid",
    "shield-slash-regular": "shield-slash-regular",
    "shield-slash-solid": "shield-slash-solid",
    "sort-ascending-regular": "sort-ascending-regular",
    "sort-ascending-solid": "sort-ascending-solid",
    "sort-descending-regular": "sort-descending-regular",
    "sort-descending-solid": "sort-descending-solid",
    "spacing-horizontal-regular": "spacing-horizontal-regular",
    "spacing-horizontal-solid": "spacing-horizontal-solid",
    "spacing-vertical-regular": "spacing-vertical-regular",
    "spacing-vertical-solid": "spacing-vertical-solid",
    "star-full-regular": "star-full-regular",
    "star-full-solid": "star-full-solid",
    "star-half-full-regular": "star-half-full-regular",
    "star-half-full-solid": "star-half-full-solid",
    "star-regular": "star-regular",
    "star-solid": "star-solid",
    "stop-full-solid": "stop-full-solid",
    "stop-regular": "stop-regular",
    "stop-solid": "stop-solid",
    "sync-regular": "sync-regular",
    "sync-solid": "sync-solid",
    "table-list-regular": "table-list-regular",
    "table-list-solid": "table-list-solid",
    "trash-close-regular": "trash-close-regular",
    "trash-close-solid": "trash-close-solid",
    "trash-regular": "trash-regular",
    "trash-solid": "trash-solid",
    "trash-slash-regular": "trash-slash-regular",
    "trash-slash-solid": "trash-slash-solid",
    "undo-regular": "undo-regular",
    "undo-solid": "undo-solid",
    "unlink-regular": "unlink-regular",
    "unlink-solid": "unlink-solid",
    "video-close-regular": "video-close-regular",
    "video-close-solid": "video-close-solid",
    "video-plus-regular": "video-plus-regular",
    "video-plus-solid": "video-plus-solid",
    "video-regular": "video-regular",
    "video-solid": "video-solid",
    "view-add-regular": "view-add-regular",
    "view-add-solid": "view-add-solid",
    "view-board-regular": "view-board-regular",
    "view-board-solid": "view-board-solid",
    "view-card-regular": "view-card-regular",
    "view-card-solid": "view-card-solid",
    "view-list-regular": "view-list-regular",
    "view-list-solid": "view-list-solid",
    "volume-down-regular": "volume-down-regular",
    "volume-down-solid": "volume-down-solid",
    "volume-regular": "volume-regular",
    "volume-solid": "volume-solid",
    "volume-slash-regular": "volume-slash-regular",
    "volume-slash-solid": "volume-slash-solid",
    "volume-up-regular": "volume-up-regular",
    "volume-up-solid": "volume-up-solid",
    "warning-circle-full-solid": "warning-circle-full-solid",
    "warning-circle-regular": "warning-circle-regular",
    "warning-circle-solid": "warning-circle-solid",
    "warning-full-solid": "warning-full-solid",
    "warning-regular": "warning-regular",
    "warning-solid": "warning-solid",
} as const

export type fajnyIconsType = keyof typeof fajnyIcons

/*==================== Text align ====================*/

const textAlign = {
    left: "left",
    center: "center",
    right: "right",
    justify: "justify",
    inherit: "inherit",
    initial: "initial",
    revert: "revert",
    "revert-layer": "revert-layer",
    unset: "unset",
} as const

export type textAlignType = keyof typeof textAlign

/*==================== Spacers ====================*/

const spacers = {
    xxl: "xxl",
    xl: "xl",
    l: "l",
    m: "m",
    s: "s",
    xs: "xs",
    xxs: "xxs",
} as const

export type spacersType = keyof typeof spacers

/*==================== Grid ====================*/

/* Justify items */

const gridJustifyItems = {
    start: "start",
    end: "end",
    center: "center",
    stretch: "stretch",
} as const

export type gridJustifyItemsType = keyof typeof gridJustifyItems

/* Align items */

const gridAlignItems = {
    start: "start",
    end: "end",
    center: "center",
    stretch: "stretch",
} as const

export type gridAlignItemsType = keyof typeof gridAlignItems

/* Justify content */

const gridJustifyContent = {
    start: "start",
    end: "end",
    center: "center",
    stretch: "stretch",
    "space-around": "space-around",
    "space-between": "space-between",
    "space-evenly": "space-evenly",
} as const

export type gridJustifyContentType = keyof typeof gridJustifyContent

/* Align content */

const gridAlignContent = {
    start: "start",
    end: "end",
    center: "center",
    stretch: "stretch",
    "space-around": "space-around",
    "space-between": "space-between",
    "space-evenly": "space-evenly",
} as const

export type gridAlignContentType = keyof typeof gridAlignContent

/*==================== Flexbox ====================*/

/* Direction */

const flexDirection = {
    row: "row",
    "row-reverse": "row-reverse",
    column: "column",
    "column-reverse": "column-reverse",
} as const

export type flexDirectionType = keyof typeof flexDirection

/* Wrap */

const flexWrap = {
    nowrap: "nowrap",
    wrap: "wrap",
    "wrap-reverse": "wrap-reverse",
} as const

export type flexWrapType = keyof typeof flexWrap

/* Justify */

const flexJustify = {
    "flex-start": "flex-start",
    "flex-end": "flex-end",
    center: "center",
    "space-between": "space-between",
    "space-around": "space-around",
    "space-evenly": "space-evenly",
} as const

export type flexJustifyType = keyof typeof flexJustify

/* Align */

const flexAlign = {
    stretch: "stretch",
    "flex-start": "flex-start",
    "flex-end": "flex-end",
    center: "center",
    baseline: "baseline",
} as const

export type flexAlignType = keyof typeof flexAlign

/*==================== Colors ====================*/

/* Fajny colors */

const fajnyColors = {
    black: "black",
    white: "white",
    "gray-50": "gray-50",
    "gray-100": "gray-100",
    "gray-200": "gray-200",
    "gray-300": "gray-300",
    "gray-400": "gray-400",
    "gray-500": "gray-500",
    "gray-600": "gray-600",
    "gray-700": "gray-700",
    "gray-800": "gray-800",
    "gray-900": "gray-900",
    "primary-50": "primary-50",
    "primary-100": "primary-100",
    "primary-200": "primary-200",
    "primary-300": "primary-300",
    "primary-400": "primary-400",
    "primary-500": "primary-500",
    "primary-600": "primary-600",
    "primary-700": "primary-700",
    "primary-800": "primary-800",
    "primary-900": "primary-900",
    "secondary-50": "secondary-50",
    "secondary-100": "secondary-100",
    "secondary-200": "secondary-200",
    "secondary-300": "secondary-300",
    "secondary-400": "secondary-400",
    "secondary-500": "secondary-500",
    "secondary-600": "secondary-600",
    "secondary-700": "secondary-700",
    "secondary-800": "secondary-800",
    "secondary-900": "secondary-900",
    "success-50": "success-50",
    "success-100": "success-100",
    "success-200": "success-200",
    "success-300": "success-300",
    "success-400": "success-400",
    "success-500": "success-500",
    "success-600": "success-600",
    "success-700": "success-700",
    "success-800": "success-800",
    "success-900": "success-900",
    "danger-50": "danger-50",
    "danger-100": "danger-100",
    "danger-200": "danger-200",
    "danger-300": "danger-300",
    "danger-400": "danger-400",
    "danger-500": "danger-500",
    "danger-600": "danger-600",
    "danger-700": "danger-700",
    "danger-800": "danger-800",
    "danger-900": "danger-900",
    "warning-50": "warning-50",
    "warning-100": "warning-100",
    "warning-200": "warning-200",
    "warning-300": "warning-300",
    "warning-400": "warning-400",
    "warning-500": "warning-500",
    "warning-600": "warning-600",
    "warning-700": "warning-700",
    "warning-800": "warning-800",
    "warning-900": "warning-900",
} as const

export type fajnyColorsType = keyof typeof fajnyColors

/* Colors short */

const colorsShort = {
    primary: "primary",
    secondary: "secondary",
    success: "success",
    danger: "danger",
    warning: "warning",
    gray: "gray",
    black: "black",
    white: "white",
} as const

export type colorsShortType = keyof typeof colorsShort

/* Colors hover */

const colorsHover = {
    primary: "primary",
    secondary: "secondary",
    success: "success",
    danger: "danger",
    warning: "warning",
    white: "white",
} as const

export type colorsHoverType = keyof typeof colorsHover

/*==================== Object fit ====================*/

const objectFit = {
    contain: "contain",
    cover: "cover",
    fill: "fill",
    none: "none",
    "scale-down": "scale-down",
    inherit: "inherit",
    initial: "initial",
    revert: "revert",
    "revert-layer": "revert-layer",
    unset: "unset",
} as const

export type objectFitType = keyof typeof objectFit

/*==================== Inputs ====================*/

/* Validation */

const validation = {
    passed: "passed",
    "not-passed": "not-passed",
} as const

export type validationTypes = keyof typeof validation